# Generated by Django 3.2.5 on 2021-09-23 20:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.UUID('b7ed148e-e1d2-4803-91f1-001d147ca532'), primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=36, unique=True)),
                ('password', models.CharField(max_length=36)),
            ],
        ),
    ]
